export const ANIMALS_ACTION_TYPES = {
	FETCH_ANIMALS_START: 'FETCH_ANIMALS_START',
	FETCH_ANIMALS_SUCCESS: 'FETCH_ANIMALS_SUCCESS',
	FETCH_ANIMALS_FAILURE: 'FETCH_ANIMALS_FAILURE',

	FETCH_ONE_ANIMAL_START: 'FETCH_ONE_ANIMAL_START',
	FETCH_ONE_ANIMAL_SUCCESS: 'FETCH_ONE_ANIMAL_SUCCESS',
	FETCH_ONE_ANIMAL_FAILURE: 'FETCH_ONE_ANIMAL_FAILURE'
}
