export const USER_ACTIONS = {
    FETCH_USER_START: 'FETCH_USER_START',
	FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
    FETCH_USER_FAILURE: 'FETCH_USER_FAILURE',
    
	USER_LOGOUT: 'USER_LOGOUT',
	USER_LOGIN: 'USER_LOGIN',
}